services:
  app:
    container_name: app
    image: rafatsu/distcomp:1.0.0
    restart: always
    environment:
      - DB_URL=mysql+pymysql://root:123@database/mysql_database
      - ADMIN_USER=brivaldo
      - SECRET_KEY=d5zmAsUt3bZdZrBjhcpJ7T2ocQgmVXfM
    ports:
      - 8080:8080
    depends_on:
      - database
    

  database:
    container_name: db_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always