services:
  app:
    container_name: app
    image: app:1.0
    restart: always
    environment:
      - DB_URL=mysql+pymysql://root:123@db_container:3306/mysql_database
      - ADMIN_USER=brivaldo
      - ADMIN_PASSWORD=123
      - SECRET_KEY=d5zmAsUt3bZdZrBjhcpJ7T2ocQgmVXfM
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - dbbridge
    volumes:
      - ./instance:/app/instance
    
  database:
    container_name: db_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql_database
    ports:
      - "3306:3306"
    restart: always
    networks:
      - dbbridge
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  dbbridge:
    driver: bridge

volumes:
  mysql_data: